# Activated by default (see application.properties). Optimized for local development.

spring.jpa.show-sql=true
logging.level.com.tasktracker=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
